#!/usr/bin/env bash

set -e
set -o pipefail

err() { notify-send 'p' 'Something bad happened :('; }
trap err ERR

win="$(xdotool getactivewindow)"
list="$(p l)" || exit
key="$(sort <<< "$list" | dmenu "$@")" || exit
if [[ -n "$key" ]]; then
	pw="$(p p "$key" | head -n1)"
	xdotool type --delay 0 --window "$win" --clearmodifiers -- "$pw"
fi
