#!/usr/bin/env bash

set -e
set -o pipefail

win="$(xdotool getactivewindow)"
key="$(p l | dmenu "$@")" || exit
if [[ -n "$key" ]]; then
	pw="$(p p "$key" | head -n1)"
	xdotool type --delay 0 --window "$win" --clearmodifiers -- "$pw"
fi
